[build]
  command = "npm install && npm run build"
  publish = "build"
  functions = "netlify/functions"  # Remove se não estiver usando funções serverless

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.8.1"
  CI = "false"  # Desativa comportamento específico de CI que pode causar problemas
  DISABLE_ESLINT_PLUGIN = "true"
  GENERATE_SOURCEMAP = "false"  # Melhora performance do build

[context.production.environment]
  REACT_APP_ENV = "production"

# Configuração essencial para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers para melhor segurança e performance
[headers]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' https://saudememora.onrender.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https://saudememora.onrender.com;
      frame-src 'none';
      object-src 'none';
    """


# Configurações opcionais para melhorar o tempo de build
[build.processing]
  skip_processing = true